language: node_js

node_js:
  - "10.14.2"

cache:
  directories:
    - ./node_modules
branches:
  only:
    - master
    - develop

install:
  - npm install

script:
  - npm run build

after_success: |
  if [ -n "$GITHUB_TOKEN" ]; then
  if : branch = master
    cd "$TRAVIS_BUILD_DIR"
    cd dist
    cd portfolio
    git init
    git checkout -b master
    git add .
    git -c user.name='ps11_builder' -c user.email='ps11_builder' commit -m init
    git push -f -q https://ps011:$GITHUB_TOKEN@github.com/ps011/ps011.github.io.git master &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
  if : branch = develop
  cd "$TRAVIS_BUILD_DIR"
     cd dist
     cd portfolio
     git init
     git checkout -b master
     git add .
     git -c user.name='ps11_builder' -c user.email='ps11_builder' commit -m init
     git push -f -q https://ps011:$GITHUB_TOKEN@github.com/ps011/ps11 gh-pages &2>/dev/null
     cd "$TRAVIS_BUILD_DIR"
